Refactored code (eg. to use ES6) and implemented to remove menu from …
katable/menu_service pull request #2
Opened 2018-10-30 02:45 UTC by TonyWu5

…some of the restaurants after seeding (since realistically, menus for some restaurants are not avalable on OpenTable).

2018-10-30 20:53 UTC, az9222 commented on database/menuSeeding.js
> +    price: '$' + faker.commerce.price().toString()};
move the bracket to be with the parentheses: });

2018-10-31 17:56 UTC, az9222 commented
Test

2018-10-31 17:58 UTC, az9222 requested changes

2018-10-31 17:58 UTC, az9222 commented on database/menuSeeding.js
>    return {
If you wanted to make this like es6 you could even just do return {restaurantID etc.} because when the keys & values are the same you can just write it once if you want to

2018-10-31 17:58 UTC, az9222 commented on database/menuSeeding.js
>      newMenu.save( (err) => {
fix spacing

2018-10-31 17:58 UTC, az9222 commented on database/menuSeeding.js
> +    price: '$' + faker.commerce.price().toString()};
move the bracket to be with the parentheses: });

2018-10-31 17:58 UTC, az9222 commented on database/menuSeeding.js
> +      if (err) {
how about an else statement?

2018-10-31 17:58 UTC, az9222 commented on client/src/index.jsx
>  import ReactDOM from 'react-dom';
you also need to import react

2018-10-31 17:58 UTC, az9222 commented on database/menuSeeding.js
> +        dishes: Array(9).fill(null).map(() => generateDishNameAndPrice())
why fill with null?

2018-10-31 17:58 UTC, az9222 commented on .eslintrc
> +{
testing

2018-10-31 18:01 UTC, TonyWu5 commented on database/menuSeeding.js
> +        dishes: Array(9).fill(null).map(() => generateDishNameAndPrice())
if not filled with null, mapping wouldn't work as there wouldn't be any element in the array...

2018-10-31 18:03 UTC, TonyWu5 commented on database/menuSeeding.js
> +      if (err) {
decided not to do anything if no error occurs.

2018-10-31 18:09 UTC, TonyWu5 commented on database/menuSeeding.js
>    return {
agreed. thanks for the reminder.

2018-10-31 18:19 UTC, merged